apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::826114294860:role/UdacityFlaskDeployCBKubectlRole
      username: voclabs/user2176828=9c77e4e0-ac23-11eb-8a05-4f2aff36c098
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::826114294860:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-10DVX8WJSO9JU
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-11T11:16:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1631"
  uid: 86402a4e-a9ff-4721-8c24-f0c4258f7440
